x-client-common: &client-common
  env_file:
    - .env
  restart: unless-stopped
  networks:
    - app-network
  extra_hosts:
    - "host.docker.internal:host-gateway"

x-client-build-args: &client-build-args
  args:
    - NEXT_PUBLIC_API_BASEPATH=${NEXT_PUBLIC_API_BASEPATH}
    - API_BASEPATH=${API_BASEPATH}
    - NEXT_PUBLIC_PUBLIC_API_KEY=${NEXT_PUBLIC_PUBLIC_API_KEY}
    - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}

services:
  client:
    <<: *client-common
    build:
      context: .
      dockerfile: Dockerfile
      <<: *client-build-args
    ports:
      - "3000:3000"

networks:
  app-network:
    driver: bridge

