import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sawarabi = localFont({
  src: "./fonts/SawarabiGothic-Regular.ttf",
  variable: "--font-sawarabi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sawarabi.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
